name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          path: 'HexaMC-source'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/HexaMC-source HexaMC-${{ env.VERSION }}
          mv HexaMC-Linux-Qt6-Portable*/HexaMC-portable.tar.gz HexaMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv HexaMC-Linux-Qt6*/HexaMC.tar.gz HexaMC-Linux-Qt6-${{ env.VERSION }}.tar.gz          
          mv HexaMC-Linux-Portable*/HexaMC-portable.tar.gz HexaMC-Linux-Portable-${{ env.VERSION }}.tar.gz
          mv HexaMC-Linux*/HexaMC.tar.gz HexaMC-Linux-${{ env.VERSION }}.tar.gz
          mv HexaMC-*.AppImage/HexaMC-*.AppImage HexaMC-Linux-${{ env.VERSION }}-x86_64.AppImage
          mv HexaMC-macOS-Legacy*/HexaMC.tar.gz HexaMC-macOS-Legacy-${{ env.VERSION }}.tar.gz
          mv HexaMC-macOS*/HexaMC.tar.gz HexaMC-macOS-${{ env.VERSION }}.tar.gz

          tar -czf HexaMC-${{ env.VERSION }}.tar.gz HexaMC-${{ env.VERSION }}

          for d in HexaMC-Windows-*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="HexaMC-Windows"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv HexaMC-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: HexaMC ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            HexaMC-Linux-${{ env.VERSION }}.tar.gz
            HexaMC-Linux-Portable-${{ env.VERSION }}.tar.gz
            HexaMC-Linux-${{ env.VERSION }}-x86_64.AppImage
            HexaMC-Windows-Legacy-${{ env.VERSION }}.zip
            HexaMC-Linux-Qt6-${{ env.VERSION }}.tar.gz
            HexaMC-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            HexaMC-Windows-Legacy-Portable-${{ env.VERSION }}.zip
            HexaMC-Windows-Legacy-Setup-${{ env.VERSION }}.exe
            HexaMC-Windows-${{ env.VERSION }}.zip
            HexaMC-Windows-Portable-${{ env.VERSION }}.zip
            HexaMC-Windows-Setup-${{ env.VERSION }}.exe
            HexaMC-macOS-${{ env.VERSION }}.tar.gz
            HexaMC-macOS-Legacy-${{ env.VERSION }}.tar.gz
            HexaMC-${{ env.VERSION }}.tar.gz
